const userController = require('../controllers/userController.js')
const friendsController = require('../controllers/friendsController.js')
const occasionController = require('../controllers/occasionController.js')
const categoryController = require('../controllers/categoryController.js')

const express = require('express');
const router = express.Router();
 
// router.get('/getalldtlcat/:CatID/:SubCatID', categoryController.getAllDtlCat)
// router.post('/categoryimgsave', categoryController.CategoryImgSave)
// router.delete('/delfrndrqts/:frommob/:tomob', friendsController.delFrndRqts)
// router.put('/friendsstatupdt/:toid/:frommob', friendsController.friendsStatUpdt)
// router.get('/getrqstrcvd/:userID', friendsController.getRqstRcvdByUid)
// router.get('/getmobilesbyuid/:userID', friendsController.getMobilesByUid)
// router.post('/friendsdtlsave', friendsController.friendsDtlSave)
// router.get('/getusrocc/:userID', occasionController.getUsrOcc)
// router.get('/getoccbydate/:userID', occasionController.getOccByDate)
// router.post('/useroccsave', occasionController.userOccSave)
// router.delete('/deleteGiftCat/:userID/:SubName', categoryController.deleteGiftCat)
// router.get('/getcatcount/:userID/:CatID', categoryController.getCatCount)
// router.get('/getonecat/:userID/:CatID', categoryController.getOneCat)
// router.get('/getallcats', categoryController.getAllCats)
// router.get('/getcategories/:userID', categoryController.getCategories)
// router.get('/getsubcat/:catID', categoryController.getSubCat)
// router.post('/giftcatsave', categoryController.giftCatSave)
// router.post('/profileimgsave', userController.ProfileImgSave)
   
// router.get('/getuserpic/:userID', userController.getUserPic)
// router.post('/addlogin', userController.addLogin)
// router.get('/getlogin/:userID/:Password', userController.getLogin)
// router.get('/getadmin/:userID/:Password', userController.getAdmin)
// router.post('/adduser', userController.addUser)
// // router.post('/adduseraddr', userController.addUserAddr)
// router.get('/getoneuser/:userID', userController.getOneUser)
// router.put('/updtusraddr/:userID', userController.UserAddrsUpdt)
// router.put('/updtusrpic/:userID', userController.UserPicUpdt)
// router.get('/getusrbymob/:umobile', userController.getUsrByMob)
// router.get('/getifriendsbyid/:userID', friendsController.getIFriendsById)
// router.get('/getimobilesbyid/:userID', friendsController.getIMobilesById)


router.get('/getadmin/:userID/:Password', userController.getAdmin)
router.put('/updtusraddr/:UserID', userController.UserAddrsUpdt)
router.put('/updtusrpic/:UserID', userController.UserPicUpdt)
router.get('/getuseraddress/:UserID', userController.getUserAddress)
router.get('/getusrbymob/:ToMob', userController.getUsrByMob)
router.get('/getoneuser/:UserID', userController.getOneUser)
router.get('/getlogin/:UserID/:Password', userController.getLogin)
router.post('/addlogin', userController.addLogin)
router.post('/adduser', userController.addUser)
router.post('/adduseradress', userController.addUserAddress)
router.put('/addprofileimg/:UserID', userController.addProfileImage)
router.put('/updtuseraddress/:UserID', userController.updtUserAddress)
router.get('/getalluseritems', userController.getAllUserItems)
router.post('/adduserwishlist', userController.addUserWishList)
router.get('/getuseritemsbyid/:UserID', userController.getUserItemsByID)
router.put('/updtusrwishlist/:UserID/:ItemID', userController.UpdtUserWishList)
router.get('/getuseritemscnt/:UserID', userController.getUserItemsCount)

module.exports = router